# Custom hors langue

[ejs.app]
title = "PSU Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/PlaySorbonne/PSU-Launcher/"
mediaTwitterURL = "https://twitter.com/PlaySorbonneU"
mediaInstagramURL = "https://www.instagram.com/play_sorbonne_u/"
mediaYouTubeURL = "https://www.youtube.com/@PlaySorbonne"
mediaDiscordURL = "https://discord.gg/HWhRdvxraJ"

[ejs.settings]
sourceGithubLink = "https://github.com/PlaySorbonne/PSU-Launcher/"
supportLink = "https://github.com/PlaySorbonne/PSU-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le lanceur PSU"
welcomeDescription = "Nous sommes Play Sorbonne Université, l'association de jeux des étudiantes et étudiants de Sorbonne Université. Notre objectif est de partager la passion des jeux de plateau et des jeux vidéo et de faire découvrir le jeu sous toutes ses formes ! Si cela te plaît, alors bienvenue chez toi !"
welcomeDescCTA = "Tu n'es qu'à quelques clics du serveur PSU !"
